apiVersion: v1
kind: Service
metadata:
  name: root-domain-gateway-svc
spec:
  selector:
    app: root-domain-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP